services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui:
